### ISSUE TITLE
Failed to load map information

### ISSUE THREAD

**Issue by lilliyw** [zz5840/BanGround-Player#61]
I have tried to play a song using an official id and it loads, perfectly well. However as soon as i press the level i want to play the game in it says it failed to load the map information?

**Comment by zz5840** [comment]
The parser in this repo is only for old Bestdori map format, which is deprecated by Bestdori months ago. I have no time to fix it since I'm working on a new project now. It's recommended to use [Sonolus](https://sonolus.com/) to play all maps on Bestdori including official and community.
